######################################################################
# Automatically generated by qmake (2.01a) Fr. Mai 12 18:33:37 2017
######################################################################

CONFIG += qt
TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/KickIT.cpp
