.TH "1_BallTracking/BallTracker/_BallTrackerInterface.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
1_BallTracking/BallTracker/_BallTrackerInterface.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./2_Control/TableControl/_TableControllerInterface\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/BallStatus\&.hpp'\fP
.br
\fC#include '\&.\&./Camera/_CameraInterface\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/Vec2\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBallTrackerInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
