.TH "4_Utilities Directory Reference" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
4_Utilities Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCalculator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBConfigReader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBConfigReader\&.hpp\fP"
.br
.ti -1c
.RI "file \fBModules\&.hpp\fP"
.br
.in -1c
