.TH "3_VirtualKicker Directory Reference" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3_VirtualKicker Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVirtualKicker\&.hpp\fP"
.br
.ti -1c
.RI "file \fBVirtualKickerWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBVirtualKickerWindow\&.hpp\fP"
.br
.in -1c
