.TH "5_DataType Directory Reference" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
5_DataType Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBallStatus\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCameraConfig\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMotorConfig\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRowEnum\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTableConfig\&.hpp\fP"
.br
.ti -1c
.RI "file \fBVec2\&.hpp\fP"
.br
.in -1c
