.TH "2_Control/TableControl/_TableControllerInterface.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
2_Control/TableControl/_TableControllerInterface.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./RowControl/_RowControllerInterface\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./\&.\&./4_Utilities/Calculator\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./4_Utilities/Modules\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/BallStatus\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/Vec2\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/CameraConfig\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/TableConfig\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTableControllerInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
