.TH "BallStatus" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BallStatus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BallStatus\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBallStatus\fP (float posx, float posy, float movementx, float movementy)"
.br
.ti -1c
.RI "\fBBallStatus\fP ()"
.br
.ti -1c
.RI "float \fBgetVelocity\fP ()"
.br
.ti -1c
.RI "\fBBallStatus\fP & \fBoperator=\fP (const \fBBallStatus\fP &bs)"
.br
.ti -1c
.RI "void \fBupdate\fP (float x, float y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec2\fP \fBmovement\fP"
.br
.ti -1c
.RI "\fBVec2\fP \fBposition\fP"
.br
.ti -1c
.RI "clock_t \fBlast_update\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BallStatus::BallStatus (float posx, float posy, float movementx, float movementy)\fC [inline]\fP"

.SS "BallStatus::BallStatus ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float BallStatus::getVelocity ()\fC [inline]\fP"

.SS "\fBBallStatus\fP& BallStatus::operator= (const \fBBallStatus\fP & bs)\fC [inline]\fP"

.SS "void BallStatus::update (float x, float y)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "clock_t BallStatus::last_update"

.SS "\fBVec2\fP BallStatus::movement"

.SS "\fBVec2\fP BallStatus::position"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
