.TH "1_BallTracking/Camera/Camera.cpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
1_BallTracking/Camera/Camera.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./1_BallTracking/Camera/Camera\&.hpp'\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/CameraConfig\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc\&.hpp'\fP
.br
\fC#include 'opencv2/highgui\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "Pylon::PylonAutoInitTerm \fBautoInitTerm\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Pylon::PylonAutoInitTerm autoInitTerm"

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
