.TH "CameraConfig" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CameraConfig\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraConfig\fP ()"
.br
.ti -1c
.RI "void \fBloadConfig\fP ()"
.br
.ti -1c
.RI "void \fBsaveConfig\fP ()"
.br
.ti -1c
.RI "void \fBprintConfig\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBredLow\fP"
.br
.ti -1c
.RI "int \fBredHigh\fP"
.br
.ti -1c
.RI "int \fBgreenLow\fP"
.br
.ti -1c
.RI "int \fBgreenHigh\fP"
.br
.ti -1c
.RI "int \fBblueLow\fP"
.br
.ti -1c
.RI "int \fBblueHigh\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBpacketsize\fP"
.br
.ti -1c
.RI "int \fBexposureTime\fP"
.br
.ti -1c
.RI "int \fBoffsetx\fP"
.br
.ti -1c
.RI "int \fBoffsety\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConfigReader\fP \fBcr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CameraConfig::CameraConfig ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CameraConfig::loadConfig ()\fC [inline]\fP"

.SS "void CameraConfig::printConfig ()\fC [inline]\fP"

.SS "void CameraConfig::saveConfig ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int CameraConfig::blueHigh"

.SS "int CameraConfig::blueLow"

.SS "\fBConfigReader\fP CameraConfig::cr\fC [protected]\fP"

.SS "int CameraConfig::exposureTime"

.SS "int CameraConfig::greenHigh"

.SS "int CameraConfig::greenLow"

.SS "int CameraConfig::height"

.SS "int CameraConfig::offsetx"

.SS "int CameraConfig::offsety"

.SS "int CameraConfig::packetsize"

.SS "int CameraConfig::redHigh"

.SS "int CameraConfig::redLow"

.SS "int CameraConfig::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
