.TH "4_Utilities/ConfigReader.cpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
4_Utilities/ConfigReader.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./4_Utilities/ConfigReader\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
