.TH "FunctionNotFoundException" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionNotFoundException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Modules\&.hpp>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionNotFoundException\fP (const char *name)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBn\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FunctionNotFoundException::FunctionNotFoundException (const char * name)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string FunctionNotFoundException::n\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
