.TH "KickIT@Eclipse.cpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KickIT@Eclipse.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '1_BallTracking/BallTracker/_BallTrackerInterface\&.hpp'\fP
.br
\fC#include '2_Control/MotorCommunication/_MotorCommunicatorInterface\&.hpp'\fP
.br
\fC#include '2_Control/TableControl/_TableControllerInterface\&.hpp'\fP
.br
\fC#include '2_Control/TableControl/TableControllerMock\&.hpp'\fP
.br
\fC#include '2_Control/TableControl/TableControllerImpl\&.hpp'\fP
.br
\fC#include '3_VirtualKicker/VirtualKicker\&.hpp'\fP
.br
\fC#include '4_Utilities/Calculator\&.hpp'\fP
.br
\fC#include '4_Utilities/Modules\&.hpp'\fP
.br
\fC#include '5_DataType/MotorConfig\&.hpp'\fP
.br
\fC#include '5_DataType/TableConfig\&.hpp'\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMODE\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MODE   4"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
