.TH "4_Utilities/Modules.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
4_Utilities/Modules.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <exception>\fP
.br
\fC#include '\&.\&./4_Utilities/ConfigReader\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunctionNotFoundException\fP"
.br
.ti -1c
.RI "class \fBFunctionAllreadyRegistered\fP"
.br
.ti -1c
.RI "class \fBModules\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBfp\fP) (std::vector< void * > *)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* fp) (std::vector< void * > *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
