.TH "MotorCommunicatorInterface" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MotorCommunicatorInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <_MotorCommunicatorInterface\&.hpp>\fP
.PP
Inherited by \fBMotorComPS01Impl\fP, and \fBMotorComRS01Impl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlinearMovement\fP (int position)=0"
.br
.ti -1c
.RI "virtual void \fBrotate\fP (int amount)"
.br
.ti -1c
.RI "virtual \fB~MotorCommunicatorInterface\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdriverInit\fP ()=0"
.br
.ti -1c
.RI "int \fBswitchedNibbleT\fP ()"
.br
.ti -1c
.RI "int \fBswitchedNibbleR\fP ()"
.br
.ti -1c
.RI "int \fBopenPort\fP ()"
.br
.ti -1c
.RI "void \fBframeInit\fP (int ID, int DLC, int Data_0, int Data_1, int Data_2, int Data_3, int Data_4, int Data_5, int Data_6, int Data_7)"
.br
.ti -1c
.RI "int \fBsendPort\fP (struct can_frame *frame)"
.br
.ti -1c
.RI "void \fBclosePort\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMotorConfig\fP \fBmc\fP"
.br
.ti -1c
.RI "\fBRow\fP \fBrow\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.ti -1c
.RI "int \fBsocketId\fP"
.br
.ti -1c
.RI "char \fBnibbleTranslational\fP = 1"
.br
.ti -1c
.RI "char \fBnibbleRotary\fP = 1"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual MotorCommunicatorInterface::~MotorCommunicatorInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void MotorCommunicatorInterface::closePort ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void MotorCommunicatorInterface::driverInit ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBMotorComPS01Impl\fP, and \fBMotorComRS01Impl\fP\&.
.SS "void MotorCommunicatorInterface::frameInit (int ID, int DLC, int Data_0, int Data_1, int Data_2, int Data_3, int Data_4, int Data_5, int Data_6, int Data_7)\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void MotorCommunicatorInterface::linearMovement (int position)\fC [pure virtual]\fP"

.PP
Implemented in \fBMotorComPS01Impl\fP, and \fBMotorComRS01Impl\fP\&.
.SS "int MotorCommunicatorInterface::openPort ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual void MotorCommunicatorInterface::rotate (int amount)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBMotorComRS01Impl\fP\&.
.SS "int MotorCommunicatorInterface::sendPort (struct can_frame * frame)\fC [inline]\fP, \fC [protected]\fP"

.SS "int MotorCommunicatorInterface::switchedNibbleR ()\fC [inline]\fP, \fC [protected]\fP"

.SS "int MotorCommunicatorInterface::switchedNibbleT ()\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMotorConfig\fP MotorCommunicatorInterface::mc\fC [protected]\fP"

.SS "char MotorCommunicatorInterface::nibbleRotary = 1\fC [protected]\fP"

.SS "char MotorCommunicatorInterface::nibbleTranslational = 1\fC [protected]\fP"

.SS "char* MotorCommunicatorInterface::port\fC [protected]\fP"

.SS "\fBRow\fP MotorCommunicatorInterface::row\fC [protected]\fP"

.SS "int MotorCommunicatorInterface::socketId\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
