.TH "2_Control/MotorCommunication/MotorComPS01Impl.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
2_Control/MotorCommunication/MotorComPS01Impl.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <net/if\&.h>\fP
.br
\fC#include <linux/can\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./5_DataType/RowEnum\&.hpp'\fP
.br
\fC#include '_MotorCommunicatorInterface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMotorComPS01Impl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
