.TH "MotorComRS01Impl" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MotorComRS01Impl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MotorComRS01Impl\&.hpp>\fP
.PP
Inherits \fBMotorCommunicatorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotorComRS01Impl\fP (\fBRow\fP r)"
.br
.ti -1c
.RI "void \fBlinearMovement\fP (int position)"
.br
.ti -1c
.RI "void \fBrotate\fP (int amount)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBdriverInit\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MotorComRS01Impl::MotorComRS01Impl (\fBRow\fP r)"

.SH "Member Function Documentation"
.PP 
.SS "void MotorComRS01Impl::driverInit ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBMotorCommunicatorInterface\fP\&.
.SS "void MotorComRS01Impl::linearMovement (int position)\fC [virtual]\fP"

.PP
Implements \fBMotorCommunicatorInterface\fP\&.
.SS "void MotorComRS01Impl::rotate (int amount)\fC [virtual]\fP"

.PP
Reimplemented from \fBMotorCommunicatorInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
