.TH "qt_meta_stringdata_TableControllerImpl_t" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_TableControllerImpl_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [5]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [49]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QByteArrayData qt_meta_stringdata_TableControllerImpl_t::data[5]"

.SS "char qt_meta_stringdata_TableControllerImpl_t::stringdata0[49]"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
