.TH "RowControllerMidfield" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RowControllerMidfield \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RowControllerMidfield\&.hpp>\fP
.PP
Inherits \fBRowControllerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRowControllerMidfield\fP ()"
.br
.ti -1c
.RI "void \fBmoveTo\fP (float y)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RowControllerMidfield::RowControllerMidfield ()"

.SH "Member Function Documentation"
.PP 
.SS "void RowControllerMidfield::moveTo (float y)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBRowControllerInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
