.TH "2_Control/RowControl/RowControllerMidfield.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
2_Control/RowControl/RowControllerMidfield.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '_RowControllerInterface\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRowControllerMidfield\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
