.TH "RowControllerDefense" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RowControllerDefense \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RowControllerDefense\&.hpp>\fP
.PP
Inherits \fBRowControllerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRowControllerDefense\fP ()"
.br
.ti -1c
.RI "void \fBkick\fP (int strength)"
.br
.ti -1c
.RI "virtual void \fBup\fP ()"
.br
.ti -1c
.RI "virtual void \fBdown\fP ()"
.br
.ti -1c
.RI "void \fBmoveTo\fP (float y)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBkickThread\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RowControllerDefense::RowControllerDefense ()"

.SH "Member Function Documentation"
.PP 
.SS "void RowControllerDefense::down ()\fC [virtual]\fP"

.PP
Reimplemented from \fBRowControllerInterface\fP\&.
.SS "void RowControllerDefense::kick (int strength)\fC [virtual]\fP"

.PP
Reimplemented from \fBRowControllerInterface\fP\&.
.SS "void RowControllerDefense::kickThread ()\fC [protected]\fP"

.SS "void RowControllerDefense::moveTo (float y)\fC [virtual]\fP"

.PP
Implements \fBRowControllerInterface\fP\&.
.SS "void RowControllerDefense::up ()\fC [virtual]\fP"

.PP
Reimplemented from \fBRowControllerInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
