.TH "5_DataType/RowEnum.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
5_DataType/RowEnum.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRow\fP { \fBKEEPER\fP, \fBDEFENSE\fP, \fBMIDFIELD\fP, \fBOFFENSE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRow\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKEEPER \fP\fP
.TP
\fB\fIDEFENSE \fP\fP
.TP
\fB\fIMIDFIELD \fP\fP
.TP
\fB\fIOFFENSE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
