.TH "TableConfig" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TableConfig\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableConfig\fP ()"
.br
.ti -1c
.RI "void \fBloadConfig\fP ()"
.br
.ti -1c
.RI "void \fBsaveConfig\fP ()"
.br
.ti -1c
.RI "void \fBprintConfig\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBtableHeight\fP"
.br
.ti -1c
.RI "float \fBtableWidth\fP"
.br
.ti -1c
.RI "bool \fBisKeeperActive\fP"
.br
.ti -1c
.RI "bool \fBisDefenseActive\fP"
.br
.ti -1c
.RI "bool \fBisMidfieldActive\fP"
.br
.ti -1c
.RI "bool \fBisOffenseActive\fP"
.br
.ti -1c
.RI "float \fBplayerGapDefense\fP"
.br
.ti -1c
.RI "float \fBplayerGapMidfield\fP"
.br
.ti -1c
.RI "float \fBplayerGapOffense\fP"
.br
.ti -1c
.RI "float \fBdistGoalToKeeper\fP"
.br
.ti -1c
.RI "float \fBdistGoalToDefense\fP"
.br
.ti -1c
.RI "float \fBdistGoalToMidfield\fP"
.br
.ti -1c
.RI "float \fBdistGoalToOffense\fP"
.br
.ti -1c
.RI "float \fBoffsetTopSideKeeper\fP"
.br
.ti -1c
.RI "float \fBoffsetBottomSideKeeper\fP"
.br
.ti -1c
.RI "float \fBoffsetTopSideDefense\fP"
.br
.ti -1c
.RI "float \fBoffsetBottomSideDefense\fP"
.br
.ti -1c
.RI "float \fBoffsetTopSideMidfield\fP"
.br
.ti -1c
.RI "float \fBoffsetBottomSideMidfield\fP"
.br
.ti -1c
.RI "float \fBoffsetTopSideOffense\fP"
.br
.ti -1c
.RI "float \fBoffsetBottomSideOffense\fP"
.br
.ti -1c
.RI "float \fBshotTriggerRange\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConfigReader\fP \fBcr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TableConfig::TableConfig ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void TableConfig::loadConfig ()\fC [inline]\fP"

.SS "void TableConfig::printConfig ()\fC [inline]\fP"

.SS "void TableConfig::saveConfig ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBConfigReader\fP TableConfig::cr\fC [protected]\fP"

.SS "float TableConfig::distGoalToDefense"

.SS "float TableConfig::distGoalToKeeper"

.SS "float TableConfig::distGoalToMidfield"

.SS "float TableConfig::distGoalToOffense"

.SS "bool TableConfig::isDefenseActive"

.SS "bool TableConfig::isKeeperActive"

.SS "bool TableConfig::isMidfieldActive"

.SS "bool TableConfig::isOffenseActive"

.SS "float TableConfig::offsetBottomSideDefense"

.SS "float TableConfig::offsetBottomSideKeeper"

.SS "float TableConfig::offsetBottomSideMidfield"

.SS "float TableConfig::offsetBottomSideOffense"

.SS "float TableConfig::offsetTopSideDefense"

.SS "float TableConfig::offsetTopSideKeeper"

.SS "float TableConfig::offsetTopSideMidfield"

.SS "float TableConfig::offsetTopSideOffense"

.SS "float TableConfig::playerGapDefense"

.SS "float TableConfig::playerGapMidfield"

.SS "float TableConfig::playerGapOffense"

.SS "float TableConfig::shotTriggerRange"

.SS "float TableConfig::tableHeight"

.SS "float TableConfig::tableWidth"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
