.TH "TableControllerMock" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableControllerMock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TableControllerMock\&.hpp>\fP
.PP
Inherits \fBTableControllerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableControllerMock\fP ()"
.br
.ti -1c
.RI "virtual \fB~TableControllerMock\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBsetBallPos\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBsetKickerWindow\fP (\fBVirtualKickerWindow\fP *p)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBVec2\fP \fBpixelToMM\fP (float xPixel, float yPixel)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBVirtualKickerWindow\fP * \fBwindow\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TableControllerMock::TableControllerMock ()"

.SS "TableControllerMock::~TableControllerMock ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBVec2\fP TableControllerMock::pixelToMM (float xPixel, float yPixel)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBTableControllerInterface\fP\&.
.SS "void TableControllerMock::run ()"

.SS "void TableControllerMock::setBallPos (float x, float y)\fC [virtual]\fP"

.PP
Implements \fBTableControllerInterface\fP\&.
.SS "void TableControllerMock::setKickerWindow (\fBVirtualKickerWindow\fP * p)"

.SS "void TableControllerMock::stop ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBVirtualKickerWindow\fP* TableControllerMock::window\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
