.TH "2_Control/TableControl/TableControllerImpl.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
2_Control/TableControl/TableControllerImpl.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./3_VirtualKicker/VirtualKickerWindow\&.hpp'\fP
.br
\fC#include '\&.\&./2_Control/TableControl/_TableControllerInterface\&.hpp'\fP
.br
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTableControllerImpl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
