.TH "5_DataType/Vec2.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
5_DataType/Vec2.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVec2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
