.TH "3_VirtualKicker/VirtualKickerWindow.hpp" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3_VirtualKicker/VirtualKickerWindow.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./2_Control/TableControl/_TableControllerInterface\&.hpp'\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <Qt>\fP
.br
\fC#include '\&.\&./5_DataType/BallStatus\&.hpp'\fP
.br
\fC#include '\&.\&./5_DataType/TableConfig\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVirtualKickerWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
