.TH "VirtualKicker" 3 "Mon Sep 25 2017" "KickIT@Eclipse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VirtualKicker \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VirtualKicker\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTableControllerInterface\fP * \fBgetVirtualKickerTable\fP ()"
.br
.ti -1c
.RI "static \fBVirtualKickerWindow\fP * \fBgetDisplay\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBWINDOW_SIZE_X\fP = 1200"
.br
.ti -1c
.RI "static const int \fBWINDOW_SIZE_Y\fP = 800"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBVirtualKickerWindow\fP* VirtualKicker::getDisplay ()\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBTableControllerInterface\fP* VirtualKicker::getVirtualKickerTable ()\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const int VirtualKicker::WINDOW_SIZE_X = 1200\fC [static]\fP"

.SS "const int VirtualKicker::WINDOW_SIZE_Y = 800\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for KickIT@Eclipse from the source code\&.
