######################################################################
# Automatically generated by qmake (3.0) Do. Mai 18 14:13:55 2017
######################################################################

TEMPLATE = app
QT += widgets
TARGET = KickIT@Eclipse
INCLUDEPATH += .
CONFIG += qt debug
CONFIG += thread
CONFIG += warn_off
CONFIG += C++11

# Input
HEADERS += 1_BallTracking/BallTracker/_BallTrackerInterface.hpp \
	   1_BallTracking/BallTracker/BallTrackerImpl.hpp \
	   1_BallTracking/Camera/_CameraInterface.hpp \
           1_BallTracking/Camera/Camera.hpp \
       	   2_Control/MotorCommunication/_MotorCommunicatorInterface.hpp \
           2_Control/MotorCommunication/MotorComPS01Impl.hpp \
	   2_Control/MotorCommunication/MotorComRS01Impl.hpp \
           2_Control/RowControl/_RowControllerInterface.hpp \
           2_Control/RowControl/RowControllerDefense.hpp \
           2_Control/RowControl/RowControllerKeeper.hpp \
           2_Control/RowControl/RowControllerMidfield.hpp \
           2_Control/RowControl/RowControllerOffense.hpp \
           2_Control/TableControl/_TableControllerInterface.hpp \
           2_Control/TableControl/TableControllerImpl.hpp \
           2_Control/TableControl/TableControllerMock.hpp \
           3_VirtualKicker/VirtualKicker.hpp \
           3_VirtualKicker/VirtualKickerWindow.hpp \
           4_Utilities/Calculator.hpp \
           4_Utilities/ConfigReader.hpp \
           4_Utilities/Modules.hpp \
           5_DataType/BallStatus.hpp \
           5_DataType/CameraConfig.hpp \
           5_DataType/MotorConfig.hpp \
           5_DataType/RowEnum.hpp \
           5_DataType/TableConfig.hpp \
           5_DataType/Vec2.hpp
SOURCES += KickIT@Eclipse.cpp \
           1_BallTracking/BallTracker/BallTrackerImpl.cpp \
           1_BallTracking/Camera/Camera.cpp \
	   2_Control/MotorCommunication/MotorComPS01Impl.cpp \
	   2_Control/MotorCommunication/MotorComRS01Impl.cpp \
           2_Control/RowControl/RowControllerDefense.cpp \
           2_Control/RowControl/RowControllerKeeper.cpp \
           2_Control/RowControl/RowControllerMidfield.cpp \
           2_Control/RowControl/RowControllerOffense.cpp \
           2_Control/TableControl/TableControllerImpl.cpp \
           2_Control/TableControl/TableControllerMock.cpp \
           3_VirtualKicker/VirtualKickerWindow.cpp \
           4_Utilities/ConfigReader.cpp
